### ISSUE TITLE
CRATE DONT SPAWN

### ISSUE THREAD

**Issue by ultravi0let27** [Crazy-Crew/CrazyEnvoys#144] opened 2024-07-12 17:49 UTC
### Plugin Version

1.11.2

### Server Version

1.21

### Server Platform

Paper

### Describe the bug

when i start a event no crate spawn in

### Steps to reproduce

i enter /envoy edit and then i made /envoy start

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment] 2024-07-12 17:51
They do spawn as I just tested it today, I will be closing the github issue as it's not a bug report but simply not a case of not knowing how to use the plugin which isn't a bad thing.

You should join the Discord & head to #crazy-envoys, send your `config.yml` and `locations.yml`

**Closed by ryderbelserion** 2024-07-12 17:51 UTC

**Comment by ultravi0let27** [comment] 2024-07-12 17:57
i know how to spawn the crates but in my server it dont spawn in idk why
